[build]
command = "npm run build -- --configuration production --no-ssr"
publish = "dist/portfolio-otavio/browser"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200